version: '3.8'

services:
  api:
    build: .
    image: fullstack-challenge-api
    command: ['sh', 'run.sh']
    ports:
    - '3000:3000'
    volumes:
    - .:/code
    environment:
    - NODE_ENV=development
    - NODE_PATH=.
    - PORT=3000
    - SECRET=my-secret-key-api
